### ISSUE TITLE
As a User, I want to pick "bar work" from a list of search options and be redirected to a results page

### ISSUE THREAD

**Issue by jamiecoe** [FACN7/Github-SCRUM-Example#7]
As a User, I want to pick "bar work" from a list of search options and be redirected to a results page

- [ ] Add Search component to home page #8 
- [ ] Redirect to Results page #9
- [ ] Investigate React Router for multiple routes #6
